[default]
POSTGRES_USERNAME = 'wjqagnqw'
POSTGRES_PASSWORD = 'QA_waOvWXxFomWhJ2iGhF9VIumXJrVgJ'
POSTGRES_PORT = 5432
POSTGRES_DATABASE = 'wjqagnqw'
POSTGRES_HOST = "isabelle.db.elephantsql.com"
POSTGRES_URL = "postgresql://wjqagnqw:QA_waOvWXxFomWhJ2iGhF9VIumXJrVgJ@isabelle.db.elephantsql.com/wjqagnqw"

AUTH_ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 30

SECRET_KEY = '39e3d48a93776226c9e01638d0b0e651b2a8038c869d6f9c7b0af724946e4965'

REDIS_HOST = 'localhost'
REDIS_PORT = 6379
REDIS_DB = 0
REDIS_PASSWORD='gjn87/W35ti_8k0iq4Qmjz=mJ.qByt124mg8jev'

RABBITMQ_EXCHANGE = 'chickie'
RABBITMQ_HOST = 'localhost'
RABBITMQ_QUEUE = 'chickie'
RABBITMQ_PORT = '5672'
RABBITMQ_DEFAULT_USER = 'admin'
RABBITMQ_DEFAULT_PASS = "senha123"
RABBITMQ_ROUTING_KEY = 'chickie'
RABBITMQ_EXCHANGE_NAME = 'amq.direct'

RABBITMQ_URL = "amqps://pkgswgrg:cT3eb5spXZPy-RexqGzp-duQRC7KKAs4@stingray.rmq.cloudamqp.com/pkgswgrg"

# User & Vhost	pkgswgrg
# Password	cT3eb5spXZPy-RexqGzp-duQRC7KKAs4 
# Ports	5672 (5671 for TLS)
# URL	amqps://pkgswgrg:cT3eb5spXZPy-RexqGzp-duQRC7KKAs4@stingray.rmq.cloudamqp.com/pkgswgrg 


# MONGODB_PROTOCOL = 'mongodb'
# MONGO_INITDB_ROOT_USERNAME = 'mongodbuser'
# MONGO_INITDB_ROOT_PASSWORD = 'your_mongodb_root_password'
# MONGO_INITDB_DATABASE = 'chickiedb'
# MONGODB_USERNAME = 'chickie'
# MONGODB_PASSWORD = 'mongo_password'
# MONGODB_HOST_NAME = 'localhost'
# MONGODB_DATA_DIR = '/data/db'
# MONDODB_LOG_DIR = '/dev/null'
# MONGODB_PORT = '27017'
# MONGODB_DATABASENAME = 'chickie'

# MONGODB_PROTOCOL = 'mongodb'
# MONGODB_CONNECTION_TYPE = 'srv'
# MONGODB_USERNAME = 'antoniofernandodj'
# MONGODB_PASSWORD = 'Gl544632'
# MONGODB_HOSTNAME_OR_DNS_SEEDLIST = 'cluster0.iftrw.mongodb.net'
# MONGODB_RETRY_WRITE = 'true'
# MONGODB_WRITE_CONCERN = 'majority'

CLOUDINARY_CLOUD_NAME = 'ddus7rrgr'
CLOUDINARY_API_KEY = '774835848692467'
CLOUDINARY_API_SECRET = 'mOrpB8bzKdBhVJilwob_cAdarbY'

MONGODB_URI = "mongodb+srv://antoniofernandodj:Gl544632*@cluster0.agz8o1v.mongodb.net/?retryWrites=true&w=majority"

JWT_EXPIRE_TIME = 86400
# JWT_EXPIRE_TIME = 7200
DROPBOX_APP_KEY = 'doesukj37kzw3im'
DROPBOX_APP_SECRET = 'snk0d7g6aqm9z93'
DROPBOX_ACCESS_TOKEN = 'sl.Bjtq1UuFRKcKzrme81BTfxPFnX43CZkHz14IySn3UWDiSsA1Y5tlSmRW5FUBCFrS5UYb2USF9hxHj1PQPHwolVWXUiQFynZTcwOacmG8CAvvg49bTwf1nAP7ebDeH3H0T6aEeHQBiRqY6VMkVqrUBBc'
DROPBOX_ACCOUNT_ID = 'dbid:AAAB5lMXlGef3cBfy8arvV9RxshmQqC-FhE'
DROPBOX_TOKEN_TYPE = 'bearer'
DROPBOX_UID = '858209843'
DROPBOX_OUTH2_REFRESH_TOKEN = 'oN19qGZwB0kAAAAAAAAAARlsA2jwuDReRTRmFEkfwfm774tuK9B3gCl7jsfXWFP8'

[dev]
POSTGRES_DATABASE = 'dev'

[prod]
POSTGRES_DATABASE_PROD = 'chickie'
