REDIS_PASSWORD='gjn87/W35ti_8k0iq4Qmjz=mJ.qByt124mg8jev'

POSTGRES_DATABASE = 'dev'
POSTGRES_USERNAME = 'postgres'
POSTGRES_PASSWORD = 'Senha123456'
POSTGRES_HOST = 'localhost'
POSTGRES_PORT = 5432

RABBITMQ_EXCHANGE = 'chickie'
RABBITMQ_HOST = 'localhost'
RABBITMQ_QUEUE = 'chickie'
RABBITMQ_PORT = '5672'
RABBITMQ_DEFAULT_USER = 'admin'
RABBITMQ_DEFAULT_PASS = "senha123"
RABBITMQ_ROUTING_KEY = 'chickie'
